### ISSUE TITLE
Enhancement: add juju metrics

### ISSUE THREAD

**Issue by sebastienpattyn93** [jamesbeedy/layer-redis#2]
Before implementing I was wondering if this would be a good idea to start implementing metrics in this charm. This way we can gather metrics from this charm. I was thinking about number of units and the basic metrics provided by juju, but I was wondering if there would be any other interesting metric that could be included.
Would love to hear your thoughts on this one since we are using this charm a lot.

**Comment by jamesbeedy** [comment]
@sebastienpattyn93 thats a great idea. I wrote this a while back, and haven't really given it much love since. I'm down to collaborate on bringing it up to speed, and think metrics would be a great add here. Bring it!

**Comment by jamesbeedy** [comment]
fixed by #3
